### ISSUE TITLE
SMS Collection

### ISSUE THREAD

**Issue by PeterChauYEG** [jhgaylor/hello-twilio-meteor#1]
I noticed that you created a SMS Mongo Collection on the server and the client. I didn't try your method as in the past, I've seen people just declare their collections in lib/. I believe this makes the collection available to the server and client. 

Is your declaration method effectively the same is the one I described? For more details see my fork https://github.com/PeterChauYEG/hello-twilio-meteor

**Comment by jhgaylor** [comment]
yes, the method you described is the same. Though, I would make a 'shared' folder and put the lib folder in that. that is just to be incredibly clear about where stuff that need to be available on the client and server lives. Almost everything is assumed to be common to the client and server and the shared folder just gets rid of the "almost" part.
